### ISSUE TITLE
Future of this app?

### ISSUE THREAD

**Issue by dumblob** [wejn/Odorik#1]
I'm currently considering Odorik as callback calling provider for few relatives. But I need seamless experience for them.

From my experience the biggest obstackle with using callbacks is creating the preset "association" for a given number (i.e. open web browser, go to odorik, login to odorik, then click a lot through multiple menus, then fill a huge form full of numbers, choose an unassigned callback number in the form, submit the form, write manually the chosen callback number on phone and add it to the chosen contact as primary number).

a) Dose this app help with this painful workflow?

b) Will export (or sharing with other apps) of standard iOS contacts also export the associated callback numbers (as vcard, of course)?

c) Does this app need internet connection to call a contact using callback?

d) Does this app support SMS callback request as fallback method? If so, can this be disabled/enabled or at least made explicit?

e) Any guidance how to easily compile this app for iPhone 5s and newer?

f) Any plans for binary releases (e.g. for https://altstore.io/ or http://www.cydiaimpactor.com/ or maybe even  https://apps.apple.com/us/app/testflight/id899247664 or https://www.einstore.io/features.html or https://github.com/applivery or  https://pangu8.com/sideloadly/ etc.)?

**Comment by wejn** [comment]
First off, I decided to pull this app from the AppStore this July (by terminating my iOS developer membership, because I didn't see a reason to continue paying Apple the $100/yr), so there's no way to get a binary of it now.

Re-uploading the app would require updating the code getting a fresh license for the new version of RubyMotion (because IIRC Apple doesn't allow uploading of apps compiled with older SDK than the previous version, and this app was last compiled with RM that supported iOS 11 or so), which is another quite expensive adventure.

**So if I were to recommend something, it would be to treat this app as if it didn't exist.** And look for some other way to achieve the same functionality. I'm pretty sure that hosting contacts on a CardDAV server and writing a web-app frontend would provide similar comfort as this crufty old app I haven't touched for a few years.

Having said all that, here are answers to your questions:

a) oh yes. It's pretty much "select a contact, and click a ``callback`` button" workflow. Easy.

b) uh, it's all based on system contacts, so I don't know how to answer this

c) yes, most definitely

d) no

e) get recent rubymotion, install all the gems/pods required, solve potential version conflicts and incompatibilities, upload to AppStore

f) no. I don't have a rooted phone, and will never own one. but if some store allows you to upload an unsigned app image, then the steps in (e) together with the upload should work.

Sorry I don't have better news for you.
